-- AlterTable
ALTER TABLE "Advertisement" ADD COLUMN     "clicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "impressions" INTEGER NOT NULL DEFAULT 0;
